---
# tasks file for python
- name: Add PPA for ubuntu
  include_tasks: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install python packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ python_packages }}"

- name: Configure python alternatives
  become: yes
  community.general.alternatives:
    name: python
    path: "{{ item.path }}"
    priority: "{{ item.priority }}"
  loop: "{{ python_alternatives }}"
